feat: breaking change for draft
openedx/edx-enterprise pull request #1505
Opened 2022-03-22 16:17 UTC by kiram15

**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production but edx-platform doesn't install it
    - `test-master.in` if edx-platform pins it, with a matching version
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] `make static` has been run to update webpack bundling if any static content was updated
- [ ] `./manage.py makemigrations` has been run
    - Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating migrations.
    - *Note*: This **must** be run if you modified any models.
      - It may or may not make a migration depending on exactly what you modified, but it should still be run.
    - This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command through an lms shell.
        - It would be `./manage.py lms makemigrations` in the shell.
- [ ] [Version](https://github.com/edx/edx-enterprise/blob/master/enterprise/__init__.py) bumped
- [ ] [Changelog](https://github.com/edx/edx-enterprise/blob/master/CHANGELOG.rst) record added
- [ ] Translations updated (see docs/internationalization.rst but also this isn't blocking for merge atm)

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/edx/edx-enterprise/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [GitHub Actions](https://github.com/edx/edx-enterprise/actions), verify version has been pushed to [PyPI](https://pypi.org/project/edx-enterprise/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [edx-platform](https://github.com/edx/edx-platform) to upgrade dependencies (including edx-enterprise)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in edx-platform will look for the latest version in PyPi.
    - Note: the edx-enterprise constraint in edx-platform **must** also be bumped to the latest version in PyPi.

2022-03-23 20:43 UTC, johnnagro requested changes

2022-03-23 20:43 UTC, johnnagro commented on integrated_channels/blackboard/views.py
> +            LOGGER.exception(
do you mean `LOGGER.error` since there is no exception?

2022-03-23 20:43 UTC, johnnagro commented on integrated_channels/canvas/views.py
> +            LOGGER.exception(
do you mean `LOGGER.error` since there is no exception?

2022-03-23 22:13 UTC, binodpant commented on enterprise/templates/enterprise/admin/oauth_authorization_successful.html
> +    <title>LMS Auth</title>
Should this says `LMS Auth successful`?

2022-03-23 22:14 UTC, binodpant commented on enterprise/templates/enterprise/base.html
> +    <!-- <script type="text/javascript" src="{% static 'common/js/vendor/bootstrap.bundle.js' %}"></script> -->
any reason to remove bootstrap here but keep commented?

2022-03-23 22:17 UTC, binodpant commented on integrated_channels/canvas/views.py
> +            return self.render_page(request, 'error')
are these second params after request meant to be integer status codes or string? looks like in the function it looks for status codes? 

https://github.com/openedx/edx-enterprise/pull/1505/files#diff-733346bb5d0a0dc4dda06b7f2f8be7ac3a7da7019c919ee777cbcf8c57f948a5R80

2022-03-23 22:18 UTC, binodpant approved these changes
looking great! no major issues, made a couple of minor suggestions but I think this works, great job with the pages!

2022-03-23 22:19 UTC, binodpant commented on enterprise/templates/enterprise/base.html
> +    <!-- <script type="text/javascript" src="{% static 'common/js/vendor/bootstrap.bundle.js' %}"></script> -->
not sure if other pages that use this template expect bootstrap? would double check

2022-03-24 16:21 UTC, johnnagro requested changes

2022-03-24 16:21 UTC, johnnagro commented on integrated_channels/blackboard/views.py
> +                LOGGER.exception(f"No state data found for given uuid: {state_uuid}.")
`LOGGER.error`

2022-03-24 16:21 UTC, johnnagro commented on integrated_channels/blackboard/views.py
> +                LOGGER.exception(f"No Blackboard configuration found for state: {state_uuid}")
`LOGGER.error`

2022-03-24 16:21 UTC, johnnagro commented on integrated_channels/blackboard/views.py
> +            LOGGER.exception("No global Blackboard configuration found")
`LOGGER.error`

2022-03-24 16:21 UTC, johnnagro commented on integrated_channels/blackboard/views.py
> +                LOGGER.exception("BLACKBOARD: failed to find refresh_token in auth response. "
`LOGGER.error`

2022-03-24 16:21 UTC, johnnagro commented on integrated_channels/canvas/views.py
> +                LOGGER.exception(f"No state data found for given uuid: {state_uuid}.")
`LOGGER.error`

2022-03-25 20:05 UTC, merged