feat: customizable management command to generate local enterprise data
openedx/edx-enterprise pull request #1826
Opened 2023-07-26 16:36 UTC by alex-sheehan-edx

https://2u-internal.atlassian.net/browse/ENT-7403

**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production but edx-platform doesn't install it
    - `test-master.in` if edx-platform pins it, with a matching version
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] `make static` has been run to update webpack bundling if any static content was updated
- [ ] `./manage.py makemigrations` has been run
    - Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating migrations.
    - *Note*: This **must** be run if you modified any models.
      - It may or may not make a migration depending on exactly what you modified, but it should still be run.
    - This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command through an lms shell.
        - It would be `./manage.py lms makemigrations` in the shell.
- [ ] [Version](https://github.com/openedx/edx-enterprise/blob/master/enterprise/__init__.py) bumped
- [ ] [Changelog](https://github.com/openedx/edx-enterprise/blob/master/CHANGELOG.rst) record added
- [ ] Translations updated (see docs/internationalization.rst but also this isn't blocking for merge atm)

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/openedx/edx-enterprise/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [GitHub Actions](https://github.com/openedx/edx-enterprise/actions), verify version has been pushed to [PyPI](https://pypi.org/project/edx-enterprise/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [edx-platform](https://github.com/openedx/edx-platform) to upgrade dependencies (including edx-enterprise)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in edx-platform will look for the latest version in PyPi.
    - Note: the edx-enterprise constraint in edx-platform **must** also be bumped to the latest version in PyPi.

2023-07-27 16:20 UTC, marlonkeating requested changes

2023-07-27 16:20 UTC, marlonkeating commented on enterprise/management/commands/manufacture_factory_data.py
> +                    striped_field = field.strip("--")
```suggestion
                    stripped_field = field.strip("--")
```

2023-07-27 16:24 UTC, alex-sheehan-edx commented on enterprise/management/commands/manufacture_factory_data.py
> +    return zip(a, a)
I'm sure I tested this... how was it working locally..

2023-07-27 16:26 UTC, alex-sheehan-edx commented on enterprise/management/commands/manufacture_factory_data.py
> +    import common.djangoapps.student.test.factories as _
yes... technically should be two different, although I think functionally it doesn't matter as we just need the modules imported for the subclassing to work.

2023-07-27 16:28 UTC, alex-sheehan-edx commented on enterprise/management/commands/manufacture_factory_data.py
> +        provided_model = '.'.join(path_of_model[:-1]) + '.' + convert_to_pascal(path_of_model[-1])
being extra careful + it felt cleaner as everything else in the command was snake case so it gives flexibility to the user

2023-07-27 16:29 UTC, alex-sheehan-edx commented on enterprise/management/commands/manufacture_factory_data.py
> +        provided_model = '.'.join(path_of_model[:-1]) + '.' + convert_to_pascal(path_of_model[-1])
```
$ ./manage.py manufacture_factory_data --model enterprise.models.enterprise_customer \
            --name "Test Enterprise" --slug "test-enterprise"
```
vs 
```
$ ./manage.py manufacture_factory_data --model enterprise.models.EnterpriseCustomer \
            --name "Test Enterprise" --slug "test-enterprise"
``` 
the point is just to have both work ¯\_(ツ)_/¯

2023-07-27 16:33 UTC, alex-sheehan-edx commented on enterprise/management/commands/manufacture_factory_data.py
> +    return zip(a, a)
yeah confirmed locally that this works

2023-07-27 16:52 UTC, alex-sheehan-edx commented on enterprise/management/commands/manufacture_factory_data.py
> +        self._called_from_command_line = True
ok I got something working were we just insert into the options object/namespace

2023-07-27 17:15 UTC, marlonkeating commented on enterprise/management/commands/manufacture_factory_data.py
> +    return zip(a, a)
Double-checked, and confirmed your current method works.  I missed that you're using an iterator over a single list, which zip will keep iterating through.

2023-07-27 17:23 UTC, marlonkeating commented on enterprise/management/commands/manufacture_factory_data.py
> +        self._called_from_command_line = True
I'm more concerned about `self._called_from_command_line`.  My understanding of python conventions is that by setting properties that begin with an underscore, we're relying on an internal implementation detail of Command that is subject to change.

2023-07-28 14:58 UTC, adamstankiewicz commented
@alex-sheehan-edx [curious] Just seeking clarification on the approach here: how does this new command relate to the existing `seed_enterprise_devstack_data` command? Is the intent to deprecate that existing one in favor of this new one? It might be confusing to have 2 commands documented doing seemingly somewhat similar things.

2023-07-28 17:40 UTC, alex-sheehan-edx commented
> 



> Member

The hope is to deprecate the old one! But there are also some use cases for this that I think apply outside of that script that I will try and highlight 😄

2023-07-28 17:41 UTC, alex-sheehan-edx commented
> @alex-sheehan-edx [curious] Just seeking clarification on the approach here: how does this new command relate to the existing `seed_enterprise_devstack_data` command? Is the intent to deprecate that existing one in favor of this new one? It might be confusing to have 2 commands documented doing seemingly somewhat similar things.

@adamstankiewicz The hope is to deprecate the old one! But there are also some use cases for this that I think apply outside of that script that I will try and highlight 😄

2023-07-31 13:06 UTC, johnnagro commented
> @alex-sheehan-edx [curious] Just seeking clarification on the approach here: how does this new command relate to the existing `seed_enterprise_devstack_data` command? Is the intent to deprecate that existing one in favor of this new one? It might be confusing to have 2 commands documented doing seemingly somewhat similar things.

@adamstankiewicz imho we may keep the seed data script and/or improve it with what we've learned here. the idea with this command - following the unix philosophy - is to make a simple, dedicated provisioning utility that can be used stand-alone or used as part of a script. this should allow us to more easily make more seed data scripts tailored to the specific needs of a feature epic.

2023-07-31 17:29 UTC, johnnagro approved these changes
looks great so far. would like to see some example scripts which utilize it.

2023-07-31 17:59 UTC, marlonkeating commented on enterprise/management/commands/manufacture_factory_data.py
> +        self._called_from_command_line = True
In reading up a bit more on python conventions, I don't see a strong consensus on whether subclasses should be using single-underscored variables from parent classes.  There's always the risk of a future version of BaseCommand changing what they deem to be an implementation detail and we only find out by this breaking on our end, but I don't see a way around that at present (without copying the whole BaseCommand class).

2023-07-31 19:16 UTC, alex-sheehan-edx commented on requirements/common_constraints.txt
> +
uhm no, what's weird is that I'm pretty sure `make upgrade` did this 🤔

2023-07-31 20:34 UTC, alex-sheehan-edx commented on tests/test_enterprise/management/test_manufacture_data.py
> +def call_command(command_name, *args, **options):
I had to redefine call_command to allow us to use unrecognized args

2023-08-01 14:59 UTC, marlonkeating approved these changes

2023-08-01 18:21 UTC, merged