fix: update group invite and removal notification tasks
openedx/edx-enterprise pull request #2089
Opened 2024-05-01 23:25 UTC by katrinan029

https://2u-internal.atlassian.net/browse/ENT-8857

**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production but edx-platform doesn't install it
    - `test-master.in` if edx-platform pins it, with a matching version
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] `make static` has been run to update webpack bundling if any static content was updated
- [ ] `./manage.py makemigrations` has been run
    - Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating migrations.
    - *Note*: This **must** be run if you modified any models.
      - It may or may not make a migration depending on exactly what you modified, but it should still be run.
    - This should be run from either a venv with all the lms/edx-enterprise requirements installed or if you checked out edx-enterprise into the src directory used by lms, you can run this command through an lms shell.
        - It would be `./manage.py lms makemigrations` in the shell.
- [ ] [Version](https://github.com/openedx/edx-enterprise/blob/master/enterprise/__init__.py) bumped
- [ ] [Changelog](https://github.com/openedx/edx-enterprise/blob/master/CHANGELOG.rst) record added
- [ ] Translations updated (see docs/internationalization.rst but also this isn't blocking for merge atm)

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/openedx/edx-enterprise/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [GitHub Actions](https://github.com/openedx/edx-enterprise/actions), verify version has been pushed to [PyPI](https://pypi.org/project/edx-enterprise/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [edx-platform](https://github.com/openedx/edx-platform) to upgrade dependencies (including edx-enterprise)
    - Trigger the '[Upgrade one Python dependency](https://github.com/openedx/edx-platform/actions/workflows/upgrade-one-python-dependency.yml)' action against master in edx-platform with new version number to generate version bump PR
    - This **must** be done after the version is visible in PyPi as `make upgrade` in edx-platform will look for the latest version in PyPi.
    - Note: the edx-enterprise constraint in edx-platform **must** also be bumped to the latest version in PyPi.

2024-05-08 16:41 UTC, marlonkeating requested changes
The implementation looks good as far as I can see, but could we add unit test(s) that would have caught the original issue?

2024-05-08 16:51 UTC, alex-sheehan-edx reviewed
Small nits that apply to both sections. LMK if you wanna chat about writing tests

2024-05-08 16:51 UTC, alex-sheehan-edx commented on enterprise/tasks.py
> +    if len(pecu_emails) > 0:
NIT not necessary but you can do `if pecu_emails:` and python should equate an empty array to False

2024-05-08 16:51 UTC, alex-sheehan-edx commented on enterprise/tasks.py
> +    if len(ecus) > 0:
I don't think this check is necessary- if `ecus` is empty, it will just not iterate through the loop

2024-05-08 19:57 UTC, marlonkeating approved these changes

2024-05-09 15:12 UTC, alex-sheehan-edx approved these changes

2024-05-09 17:35 UTC, merged