fix: migrations to make it postgresql compatible.
openedx/edx-enterprise pull request #2281
Opened 2024-11-04 08:25 UTC by qasimgulzar

2024-11-04 08:25 UTC, openedx-webhooks commented
Thanks for the pull request, @qasimgulzar!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/openedx-unmaintained`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-11-13 13:34 UTC, qasimgulzar commented
@ormsbee could you please approve the workflow execution?

2024-11-15 16:22 UTC, ormsbee commented
@qasimgulzar: @iloveagent57 said that he could take a look at this one.

2024-12-10 22:33 UTC, mphilbrick211 commented
@qasimgulzar - just flagging some failing checks here.

2024-12-11 07:03 UTC, qasimgulzar commented
I will take care of it

2025-02-24 22:45 UTC, mphilbrick211 commented
Hi @openedx/2u-enterprise! Would someone be able to take a look at this?

2025-03-19 16:25 UTC, mphilbrick211 commented
> Hi @openedx/2u-enterprise! Would someone be able to take a look at this?

Friendly ping on this @openedx/enterprise-titans @openedx/2u-enterprise

2025-03-20 16:52 UTC, ormsbee requested changes
Some questions and a few minor (optional) nit suggestions.

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/blackboard/migrations/0013_alter_blackboardlearnerdatatransmissionaudit_index_together.py
> +        if 'postgresql' in db_engine:
Nit: I think this would read a bit easier if it was in an "elif" so that each set of operations is at the same indentation level, i.e.:

```python
if 'sqlite3' in db_engine:
    # ...
elif 'postgresql' in db_engine:
    # ....
else:
    # ...
```

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/cornerstone/migrations/0025_alter_cornerstonelearnerdatatransmissionaudit_index_together.py
> +                            CREATE INDEX cornerstone_cldta_85936b55_idx
Question: Why not `CREATE INDEX CONCURRENTLY` here?

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/degreed/migrations/0027_alter_degreedlearnerdatatransmissionaudit_index_together.py
> +                        CREATE INDEX degreed_dldta_85936b55_idx
Question: Why not `CREATE INDEX CONCURRENTLY` here?

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/degreed2/migrations/0019_alter_degreed2learnerdatatransmissionaudit_index_together.py
> +        ]
I'm confused by this. Why is this here? When would this ever execute for us, if it's not sqlite, postgres, or mysql?

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/integrated_channel/migrations/0028_alter_contentmetadataitemtransmission_unique_together.py
> +        if 'postgresql' in db_engine:
Same nit about using elif to reduce indentation here.

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/moodle/migrations/0023_alter_moodlelearnerdatatransmissionaudit_index_together.py
> +        raise ValueError("Unsupported database engine")
Please add a comment about why it's okay to not account for sqlite3 here.

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/sap_success_factors/migrations/0001_squashed_0022_auto_20200206_1046_squashed_0011_alter_sapsuccessfactorslearnerdatatransmissionaudit_enterprise_course_enrollment_id.py
> +            }
Question: Why was this change necessary?

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/sap_success_factors/migrations/0011_alter_sapsuccessfactorslearnerdatatransmissionaudit_index_together.py
> +                    """
NIt: I think this is okay either way, but if it's only being used once, I think you might as well inline it like you did elsewhere in this PR.

2025-03-20 16:52 UTC, ormsbee commented on integrated_channels/xapi/migrations/0011_alter_xapilearnerdatatransmissionaudit_index_together.py
> +                    migrations.RunSQL(sql=generate_index_sql(db_engine), reverse_sql="""
Nit: I think this is okay either way, but if it's only being used once, I think you might as well inline it like you did elsewhere in this PR.

2025-03-23 07:22 UTC, qasimgulzar commented on integrated_channels/blackboard/migrations/0013_alter_blackboardlearnerdatatransmissionaudit_index_together.py
> +        if 'postgresql' in db_engine:
I would agree it make sense.

2025-03-23 07:35 UTC, qasimgulzar commented on integrated_channels/cornerstone/migrations/0025_alter_cornerstonelearnerdatatransmissionaudit_index_together.py
> +                            CREATE INDEX cornerstone_cldta_85936b55_idx
I believe  it will be fresh start of database if anyone will be choosing to go with Postgresql and there will be no pre-populated data. However If I use `CONCURRENTLY` there is a potential if could have error in background which is very unlikely but there is a chance. So I believe it will only add complexity with no benefits

2025-03-23 07:35 UTC, qasimgulzar commented on integrated_channels/degreed/migrations/0027_alter_degreedlearnerdatatransmissionaudit_index_together.py
> +                        CREATE INDEX degreed_dldta_85936b55_idx
I believe  it will be fresh start of database if anyone will be choosing to go with Postgresql and there will be no pre-populated data. However If I use `CONCURRENTLY` there is a potential if could have error in background which is very unlikely but there is a chance. So I believe it will only add complexity with no benefits

2025-03-23 07:41 UTC, qasimgulzar commented on integrated_channels/degreed2/migrations/0019_alter_degreed2learnerdatatransmissionaudit_index_together.py
> +        ]
you are right I might have overthink here I can cover sqlite with else only.

2025-03-23 07:45 UTC, qasimgulzar commented on integrated_channels/integrated_channel/migrations/0028_alter_contentmetadataitemtransmission_unique_together.py
> +        if 'postgresql' in db_engine:
agree.

2025-03-23 07:58 UTC, qasimgulzar commented on integrated_channels/sap_success_factors/migrations/0001_squashed_0022_auto_20200206_1046_squashed_0011_alter_sapsuccessfactorslearnerdatatransmissionaudit_enterprise_course_enrollment_id.py
> +            }
If don't do this change the table name generated in postgresql doesn't match with the table name it generates in mysql. I believe it is because of the make table name length constraints.
The reason of pinning it is as we are using the table name while creating index in subsequent migration.
`0011_alter_sapsuccessfactorslearnerdatatransmissionaudit_index_together.py`

2025-03-23 08:01 UTC, qasimgulzar commented on integrated_channels/sap_success_factors/migrations/0011_alter_sapsuccessfactorslearnerdatatransmissionaudit_index_together.py
> +                    """
noted

2025-03-23 08:08 UTC, qasimgulzar commented on integrated_channels/xapi/migrations/0011_alter_xapilearnerdatatransmissionaudit_index_together.py
> +                    migrations.RunSQL(sql=generate_index_sql(db_engine), reverse_sql="""
noted

2025-03-28 09:55 UTC, qasimgulzar commented
@ormsbee I had accommodated your feedback please give it a look again. Also I have responded to few of your questions.

2025-04-07 20:22 UTC, ormsbee commented
@openedx/2u-enterprise: I'm planning to merge this tomorrow. Please let me know if anyone wants to look it over before I do so. Thank you.

2025-04-07 20:27 UTC, qasimgulzar commented
@ormsbee could you please approve the tests again?

2025-04-08 08:56 UTC, qasimgulzar commented
@ormsbee could you please approve the workflows now?

2025-04-08 14:28 UTC, iloveagent57 commented
@qasimgulzar @ormsbee approved by enterprise, workflows are running now.

2025-04-08 14:29 UTC, iloveagent57 approved these changes

2025-04-08 14:43 UTC, iloveagent57 commented
@qasimgulzar could you squash the commits, add a CHANGELOG entry, and bump the version, please, and then this will be ready to merge. Thanks!

2025-04-09 05:21 UTC, qasimgulzar commented
@iloveagent57 sure I will do it today

2025-04-09 05:32 UTC, qasimgulzar commented
@iloveagent57 I just pushed these changes.

[x] Update CHANGELOG.rst
[x] Bump Version [5.12.4]
[x] Squashed the commits

2025-04-09 14:12 UTC, merged